from ralium.util import UrlPath

class WindowNavigation:
    def __init__(self, current_url: UrlPath = "/") -> None: ...
    @property
    def previous(self) -> UrlPath | None: ...
    @property
    def location(self) -> UrlPath: ...
    @location.setter
    def location(self, new_url: UrlPath) -> None: ...