from .infoinsta import Info_Insta
from .chat import GPT
from .ktkt import kt
from .tik_tok import Tik_Tok
from .info_tik import Info_Tik
from .pryer import prayer_times
from .insta import instagram
from .search_pinterset import Search_Pinterest
from .soundcloud import Sound_Cloud
from .youtu import YouTube_Download
from .twitter import Twitter_Download
from .restinsta import Rest_Instagram