# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.update_order_line_item_request import UpdateOrderLineItemRequest  # noqa: E501

class TestUpdateOrderLineItemRequest(unittest.TestCase):
    """UpdateOrderLineItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderLineItemRequest:
        """Test UpdateOrderLineItemRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderLineItemRequest`
        """
        model = UpdateOrderLineItemRequest()  # noqa: E501
        if include_optional:
            return UpdateOrderLineItemRequest(
                uom = '',
                accounting_code = '',
                adjustment_liability_accounting_code = '',
                adjustment_revenue_accounting_code = '',
                amount_per_unit = 1.337,
                bill_target_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                bill_to = '',
                billing_rule = 'TriggerWithoutFulfillment',
                contract_asset_accounting_code = '',
                contract_liability_accounting_code = '',
                contract_recognized_revenue_accounting_code = '',
                custom_fields = {
                    'key' : None
                    },
                deferred_revenue_accounting_code = '',
                description = '',
                inline_discount_per_unit = 1.337,
                inline_discount_type = 'Percentage',
                invoice_group_number = '',
                is_allocation_eligible = True,
                is_unbilled = True,
                exclude_item_billing_from_revenue_accounting = True,
                exclude_item_booking_from_revenue_accounting = True,
                revenue_recognition_timing = '',
                revenue_amortization_method = '',
                item_name = '',
                item_number = '',
                item_state = 'Executing',
                item_type = 'Product',
                list_price_per_unit = 1.337,
                owner_account_number = '',
                product_code = '',
                purchase_order_number = '',
                quantity = 1.337,
                recognized_revenue_accounting_code = '',
                related_subscription_number = '',
                revenue_recognition_rule = '',
                sequence_set_id = '',
                sold_to = '',
                tax_code = '',
                tax_mode = 'TaxInclusive',
                transaction_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                transaction_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                unbilled_receivables_accounting_code = ''
            )
        else:
            return UpdateOrderLineItemRequest(
        )
        """

    def testUpdateOrderLineItemRequest(self):
        """Test UpdateOrderLineItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
