# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.reject_payment_request import RejectPaymentRequest  # noqa: E501

class TestRejectPaymentRequest(unittest.TestCase):
    """RejectPaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RejectPaymentRequest:
        """Test RejectPaymentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RejectPaymentRequest`
        """
        model = RejectPaymentRequest()  # noqa: E501
        if include_optional:
            return RejectPaymentRequest(
                gateway_reconciliation_reason = '',
                gateway_reconciliation_status = '',
                gateway_response = '',
                gateway_response_code = '',
                reference_id = '',
                second_reference_id = '',
                settled_on = ''
            )
        else:
            return RejectPaymentRequest(
        )
        """

    def testRejectPaymentRequest(self):
        """Test RejectPaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
