# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.custom_object_record_batch_action import CustomObjectRecordBatchAction  # noqa: E501

class TestCustomObjectRecordBatchAction(unittest.TestCase):
    """CustomObjectRecordBatchAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomObjectRecordBatchAction:
        """Test CustomObjectRecordBatchAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomObjectRecordBatchAction`
        """
        model = CustomObjectRecordBatchAction()  # noqa: E501
        if include_optional:
            return CustomObjectRecordBatchAction(
                allow_partial_success = True,
                ids = ["64edb2a5-2796-4e95-9559-846f8636a01b","dbfb35a3-dd2b-42c9-b8f7-eb36fed1a1e1","2c2a1810-bfef-4150-84de-50e769978e42"],
                records = {"64edb2a5-2796-4e95-9559-846f8636a01b":{"name__c":"elba43","person_id__c\"":"30c52793-8f06-41c6-b623-04829710d7a"}},
                type = 'delete'
            )
        else:
            return CustomObjectRecordBatchAction(
                type = 'delete',
        )
        """

    def testCustomObjectRecordBatchAction(self):
        """Test CustomObjectRecordBatchAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
