# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.workflow_error import WorkflowError  # noqa: E501

class TestWorkflowError(unittest.TestCase):
    """WorkflowError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowError:
        """Test WorkflowError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowError`
        """
        model = WorkflowError()  # noqa: E501
        if include_optional:
            return WorkflowError(
                code = 'invalid',
                status = 56,
                title = ''
            )
        else:
            return WorkflowError(
        )
        """

    def testWorkflowError(self):
        """Test WorkflowError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
