# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.payment_run import PaymentRun  # noqa: E501

class TestPaymentRun(unittest.TestCase):
    """PaymentRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRun:
        """Test PaymentRun
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRun`
        """
        model = PaymentRun()  # noqa: E501
        if include_optional:
            return PaymentRun(
                account_id = '',
                apply_credit_balance = True,
                auto_apply_credit_memo = True,
                auto_apply_unapplied_payment = True,
                batch = 'Batch1',
                bill_cycle_day = '1',
                billing_run_id = '',
                collect_payment = True,
                completed_on = '',
                consolidated_payment = True,
                created_by_id = '',
                created_date = '',
                currency = 'USD',
                executed_on = '',
                id = '',
                number = '',
                payment_gateway_id = '',
                process_payment_with_closed_pm = True,
                run_date = '',
                payment_gateway_number = '',
                status = 'Pending',
                target_date = '',
                updated_by_id = '',
                updated_date = '',
                organization_labels = ''
            )
        else:
            return PaymentRun(
        )
        """

    def testPaymentRun(self):
        """Test PaymentRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
