# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.get_mass_update_response import GetMassUpdateResponse  # noqa: E501

class TestGetMassUpdateResponse(unittest.TestCase):
    """GetMassUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMassUpdateResponse:
        """Test GetMassUpdateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMassUpdateResponse`
        """
        model = GetMassUpdateResponse()  # noqa: E501
        if include_optional:
            return GetMassUpdateResponse(
                action_type = '',
                ended_on = '',
                error_count = '',
                input_size = 56,
                output_size = 56,
                output_type = '',
                output_url = '',
                processed_count = '',
                started_on = '',
                status = '',
                success = True,
                success_count = '',
                total_count = '',
                uploaded_by = '',
                uploaded_on = ''
            )
        else:
            return GetMassUpdateResponse(
        )
        """

    def testGetMassUpdateResponse(self):
        """Test GetMassUpdateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
