# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.get_workflows_response import GetWorkflowsResponse  # noqa: E501

class TestGetWorkflowsResponse(unittest.TestCase):
    """GetWorkflowsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkflowsResponse:
        """Test GetWorkflowsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWorkflowsResponse`
        """
        model = GetWorkflowsResponse()  # noqa: E501
        if include_optional:
            return GetWorkflowsResponse(
                data = [
                    {"active_version":{"description":"description","id":0,"type":"Workflow::Setup","version":"version","status":"status"},"calloutTrigger":true,"timezone":"timezone","description":"description","createdAt":"createdAt","name":"name","scheduledTrigger":true,"interval":"interval","id":6,"latest_inactive_verisons":[{"createdAt":"createdAt","calloutTrigger":true,"timezone":"timezone","name":"name","scheduledTrigger":true,"description":"description","interval":"interval","id":1,"type":"Workflow::Setup","version":"version","ondemandTrigger":true,"updatedAt":"updatedAt"},{"createdAt":"createdAt","calloutTrigger":true,"timezone":"timezone","name":"name","scheduledTrigger":true,"description":"description","interval":"interval","id":1,"type":"Workflow::Setup","version":"version","ondemandTrigger":true,"updatedAt":"updatedAt"}],"ondemandTrigger":true,"status":"status","updatedAt":"updatedAt"}
                    ],
                pagination = {"next_page":"next_page","page_length":5,"page":5}
            )
        else:
            return GetWorkflowsResponse(
        )
        """

    def testGetWorkflowsResponse(self):
        """Test GetWorkflowsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
