# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.get_batch_query_job_response import GetBatchQueryJobResponse  # noqa: E501

class TestGetBatchQueryJobResponse(unittest.TestCase):
    """GetBatchQueryJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBatchQueryJobResponse:
        """Test GetBatchQueryJobResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBatchQueryJobResponse`
        """
        model = GetBatchQueryJobResponse()  # noqa: E501
        if include_optional:
            return GetBatchQueryJobResponse(
                batches = [
                    com.zuora.models.batch.batch(
                        api_version = '', 
                        batch_id = '', 
                        batch_type = 'zoql', 
                        file_id = '', 
                        full = True, 
                        message = '', 
                        name = '', 
                        query = '', 
                        record_count = '', 
                        segments = [
                            ''
                            ], 
                        status = 'submitted', 
                        localized_status = 'submitted', 
                        deleted = com.zuora.models.deleted_record.deletedRecord(
                            column = '', 
                            format = '', ), )
                    ],
                encrypted = 'pgp',
                format = 'CSV',
                id = '',
                name = '',
                partner = '',
                project = '',
                offset = 1.337,
                use_last_completed_job_queries = True,
                start_time = '',
                status = 'submitted',
                localized_status = 'submitted',
                version = 1.337,
                error_code = '',
                message = ''
            )
        else:
            return GetBatchQueryJobResponse(
        )
        """

    def testGetBatchQueryJobResponse(self):
        """Test GetBatchQueryJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
