# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.create_authorization_response import CreateAuthorizationResponse  # noqa: E501

class TestCreateAuthorizationResponse(unittest.TestCase):
    """CreateAuthorizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAuthorizationResponse:
        """Test CreateAuthorizationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAuthorizationResponse`
        """
        model = CreateAuthorizationResponse()  # noqa: E501
        if include_optional:
            return CreateAuthorizationResponse(
                gateway_order_id = '',
                payment_gateway_response = com.zuora.models.create_authorization_response_payment_gateway.CreateAuthorizationResponsePaymentGateway(
                    additional_info = com.zuora.models.additional_info.additionalInfo(), 
                    gateway_response_code = '', 
                    gateway_response_message = '', 
                    gateway_type = '', 
                    gateway_version = '', ),
                process_id = '',
                reasons = [
                    com.zuora.models.create_authorization_response_reasons.CreateAuthorizationResponseReasons(
                        code = '', 
                        message = '', )
                    ],
                request_id = '',
                result_code = '',
                result_message = '',
                success = True,
                transaction_id = ''
            )
        else:
            return CreateAuthorizationResponse(
        )
        """

    def testCreateAuthorizationResponse(self):
        """Test CreateAuthorizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
