# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.ineligible_billing_adjustment import IneligibleBillingAdjustment  # noqa: E501

class TestIneligibleBillingAdjustment(unittest.TestCase):
    """IneligibleBillingAdjustment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IneligibleBillingAdjustment:
        """Test IneligibleBillingAdjustment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IneligibleBillingAdjustment`
        """
        model = IneligibleBillingAdjustment()  # noqa: E501
        if include_optional:
            return IneligibleBillingAdjustment(
                adjustment_id = '',
                adjustment_number = '',
                amount = 1,
                billing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                charge_number = '',
                deferred_revenue_accounting_code = '',
                delivery_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                delivery_day = '',
                eligible = True,
                error_message = '',
                reason = '',
                recognized_revenue_accounting_code = '',
                revenue_recognition_rule_name = '',
                status = '',
                subscription_number = ''
            )
        else:
            return IneligibleBillingAdjustment(
        )
        """

    def testIneligibleBillingAdjustment(self):
        """Test IneligibleBillingAdjustment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
