# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.zuora.api.notifications_api import NotificationsApi  # noqa: E501


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_notification_definition(self) -> None:
        """Test case for create_notification_definition

        Create a notification definition  # noqa: E501
        """
        pass

    def test_create_or_update_email_templates(self) -> None:
        """Test case for create_or_update_email_templates

        Create or update email templates  # noqa: E501
        """
        pass

    def test_delete_email_template(self) -> None:
        """Test case for delete_email_template

        Delete an email template  # noqa: E501
        """
        pass

    def test_delete_notification_definition(self) -> None:
        """Test case for delete_notification_definition

        Delete a notification definition  # noqa: E501
        """
        pass

    def test_delete_notification_history_for_account(self) -> None:
        """Test case for delete_notification_history_for_account

        Delete notification histories for an account  # noqa: E501
        """
        pass

    def test_get_callout_history(self) -> None:
        """Test case for get_callout_history

        List callout notification histories  # noqa: E501
        """
        pass

    def test_get_email_history(self) -> None:
        """Test case for get_email_history

        List email notification histories  # noqa: E501
        """
        pass

    def test_get_email_template(self) -> None:
        """Test case for get_email_template

        Retrieve an email template  # noqa: E501
        """
        pass

    def test_get_notification_definition(self) -> None:
        """Test case for get_notification_definition

        Retrieve a notification definition  # noqa: E501
        """
        pass

    def test_get_notification_history_deletion_task(self) -> None:
        """Test case for get_notification_history_deletion_task

        Retrieve a notification history deletion task  # noqa: E501
        """
        pass

    def test_post_create_email_template(self) -> None:
        """Test case for post_create_email_template

        Create an email template  # noqa: E501
        """
        pass

    def test_query_email_templates(self) -> None:
        """Test case for query_email_templates

        List email templates  # noqa: E501
        """
        pass

    def test_query_notification_definitions(self) -> None:
        """Test case for query_notification_definitions

        List notification definitions  # noqa: E501
        """
        pass

    def test_resend_callout_notifications(self) -> None:
        """Test case for resend_callout_notifications

        Resend callout notifications  # noqa: E501
        """
        pass

    def test_resend_email_notifications(self) -> None:
        """Test case for resend_email_notifications

        Resend email notifications  # noqa: E501
        """
        pass

    def test_update_email_template(self) -> None:
        """Test case for update_email_template

        Update an email template  # noqa: E501
        """
        pass

    def test_update_notification_definition(self) -> None:
        """Test case for update_notification_definition

        Update a notification definition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
