
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-18T10:52:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2a1ce7f32a925fd0091ec1b2342bcc0d353843d",
 "version": "1.2.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
