from .content import Content

class Post(Content):
	def __init__(self, post_id: str) -> None: ...
	async def __get_post(self) -> dict: ...
	async def author(self) -> User: ...
	async def content(self) -> str: ...
	async def created(self) -> str: ...
	async def is_wiki(self) -> bool: ...
	async def likes(self) -> int: ...
