# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from armada_client.armada import job_pb2 as armada_dot_job__pb2


class JobsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJobStatus = channel.unary_unary(
                '/api.Jobs/GetJobStatus',
                request_serializer=armada_dot_job__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=armada_dot_job__pb2.JobStatusResponse.FromString,
                )
        self.GetJobDetails = channel.unary_unary(
                '/api.Jobs/GetJobDetails',
                request_serializer=armada_dot_job__pb2.JobDetailsRequest.SerializeToString,
                response_deserializer=armada_dot_job__pb2.JobDetailsResponse.FromString,
                )
        self.GetJobRunDetails = channel.unary_unary(
                '/api.Jobs/GetJobRunDetails',
                request_serializer=armada_dot_job__pb2.JobRunDetailsRequest.SerializeToString,
                response_deserializer=armada_dot_job__pb2.JobRunDetailsResponse.FromString,
                )


class JobsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobRunDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=armada_dot_job__pb2.JobStatusRequest.FromString,
                    response_serializer=armada_dot_job__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetJobDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobDetails,
                    request_deserializer=armada_dot_job__pb2.JobDetailsRequest.FromString,
                    response_serializer=armada_dot_job__pb2.JobDetailsResponse.SerializeToString,
            ),
            'GetJobRunDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobRunDetails,
                    request_deserializer=armada_dot_job__pb2.JobRunDetailsRequest.FromString,
                    response_serializer=armada_dot_job__pb2.JobRunDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Jobs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Jobs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Jobs/GetJobStatus',
            armada_dot_job__pb2.JobStatusRequest.SerializeToString,
            armada_dot_job__pb2.JobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Jobs/GetJobDetails',
            armada_dot_job__pb2.JobDetailsRequest.SerializeToString,
            armada_dot_job__pb2.JobDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobRunDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Jobs/GetJobRunDetails',
            armada_dot_job__pb2.JobRunDetailsRequest.SerializeToString,
            armada_dot_job__pb2.JobRunDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
