# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.usage_item import UsageItem  # noqa: E501

class TestUsageItem(unittest.TestCase):
    """UsageItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageItem:
        """Test UsageItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageItem`
        """
        model = UsageItem()  # noqa: E501
        if include_optional:
            return UsageItem(
                id = '',
                account_id = '',
                account_name = '',
                account_number = '',
                subscription_number = '',
                charge_number = '',
                start_date_time = '',
                unit_of_measure = '',
                quantity = '',
                source_name = '',
                file_name = '',
                status = '',
                submission_date_time = '',
                unique_key = ''
            )
        else:
            return UsageItem(
        )
        """

    def testUsageItem(self):
        """Test UsageItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
