# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.migration_client_response import MigrationClientResponse  # noqa: E501

class TestMigrationClientResponse(unittest.TestCase):
    """MigrationClientResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MigrationClientResponse:
        """Test MigrationClientResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MigrationClientResponse`
        """
        model = MigrationClientResponse()  # noqa: E501
        if include_optional:
            return MigrationClientResponse(
                email_ids = '',
                environment = '',
                id = '',
                migrated_by = 'Jane Cooper',
                migration_description = 'Migration from/to Sandbox',
                migration_end = '2020-11-01 18:00:00',
                migration_name = 'Job A',
                migration_start = '2020-11-01 18:00:00',
                response = [
                    {"componentType":"componentType","currentTargetResponse":"{}","errorMessage":"errorMessage","httpMethods":"httpMethods","description":"description","sourceResponse":"{}","segregationKey":"segregationKey","result":"result","migrationId":"migrationId","migratedOn":"2000-01-23T04:56:07.000+00:00","updateStatus":"updateStatus","disabled":"disabled","attribute":"attribute","id":"id","pathPattern":"pathPattern","previousTargetResponse":"{}","key":"key","status":"status"}
                    ],
                source_tenant_description = 'Duno',
                source_tenant_name = 'Duno',
                status = 'IN PROGRESS',
                type = ''
            )
        else:
            return MigrationClientResponse(
                id = '',
                migrated_by = 'Jane Cooper',
                migration_description = 'Migration from/to Sandbox',
                migration_end = '2020-11-01 18:00:00',
                migration_name = 'Job A',
                migration_start = '2020-11-01 18:00:00',
                source_tenant_description = 'Duno',
                source_tenant_name = 'Duno',
                status = 'IN PROGRESS',
        )
        """

    def testMigrationClientResponse(self):
        """Test MigrationClientResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
