# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.collect_debit_memo_response import CollectDebitMemoResponse  # noqa: E501

class TestCollectDebitMemoResponse(unittest.TestCase):
    """CollectDebitMemoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectDebitMemoResponse:
        """Test CollectDebitMemoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectDebitMemoResponse`
        """
        model = CollectDebitMemoResponse()  # noqa: E501
        if include_optional:
            return CollectDebitMemoResponse(
                applied_credit_memos = [
                    null
                    ],
                applied_payments = [
                    null
                    ],
                debit_memo = com.zuora.models.collect_debit_memo_response_debit_memo.CollectDebitMemoResponseDebitMemo(
                    id = '', 
                    number = '', ),
                processed_payment = com.zuora.models.collect_debit_memo_response_processed_payment.CollectDebitMemoResponseProcessedPayment(
                    amount = 1.337, 
                    gateway_id = '', 
                    gateway_response = '', 
                    gateway_response_code = '', 
                    id = '', 
                    number = '', 
                    payment_method_id = '', 
                    status = 'Processing', ),
                success = True
            )
        else:
            return CollectDebitMemoResponse(
        )
        """

    def testCollectDebitMemoResponse(self):
        """Test CollectDebitMemoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
