# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.bill_run_response import BillRunResponse  # noqa: E501

class TestBillRunResponse(unittest.TestCase):
    """BillRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillRunResponse:
        """Test BillRunResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillRunResponse`
        """
        model = BillRunResponse()  # noqa: E501
        if include_optional:
            return BillRunResponse(
                process_id = '',
                request_id = '',
                reasons = [
                    {"code":"code","message":"message"}
                    ],
                success = True,
                id = '',
                name = '',
                bill_run_number = '',
                batches = [
                    ''
                    ],
                bill_cycle_day = '',
                bill_run_filters = [
                    com.zuora.models.bill_run_filter.billRunFilter(
                        filter_type = 'Account', 
                        account_id = '', 
                        subscription_id = '', 
                        invoice_schedule_id = '', 
                        invoice_schedule_item_id = '', )
                    ],
                charge_type_to_exclude = [
                    'OneTime'
                    ],
                auto_email = True,
                auto_post = True,
                auto_renewal = True,
                no_email_for_zero_amount_invoice = True,
                schedule = com.zuora.models.schedule.schedule(
                    repeat_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    repeat_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    repeat_type = 'None', 
                    run_time = 56, 
                    weekly_on_day = [
                        'Mon'
                        ], 
                    monthly_on_end_of_month = True, ),
                scheduled_execution_time = '2023-10-19 14:24:44',
                status = 'Pending',
                invoice_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                invoice_date_offset = 56,
                invoice_date_month_offset = 56,
                invoice_date_day_of_month = 1,
                target_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                target_date_offset = 56,
                target_date_month_offset = 56,
                target_date_day_of_month = 1,
                created_by_id = '',
                created_date = '',
                updated_by_id = '',
                updated_date = ''
            )
        else:
            return BillRunResponse(
        )
        """

    def testBillRunResponse(self):
        """Test BillRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
