# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.zuora.api.debit_memos_api import DebitMemosApi  # noqa: E501


class TestDebitMemosApi(unittest.TestCase):
    """DebitMemosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DebitMemosApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_bulk_create_debit_memos(self) -> None:
        """Test case for bulk_create_debit_memos

        Create debit memos  # noqa: E501
        """
        pass

    def test_bulk_update_debit_memos(self) -> None:
        """Test case for bulk_update_debit_memos

        Update debit memos  # noqa: E501
        """
        pass

    def test_cancel_async_debit_memo(self) -> None:
        """Test case for cancel_async_debit_memo

        Cancel a Debit Memo in async  # noqa: E501
        """
        pass

    def test_cancel_debit_memo(self) -> None:
        """Test case for cancel_debit_memo

        Cancel a debit memo  # noqa: E501
        """
        pass

    def test_collect_debit_memo(self) -> None:
        """Test case for collect_debit_memo

        Collect a posted debit memo  # noqa: E501
        """
        pass

    def test_create_debit_memo_from_charge(self) -> None:
        """Test case for create_debit_memo_from_charge

        Create a debit memo from a charge  # noqa: E501
        """
        pass

    def test_create_debit_memo_from_invoice(self) -> None:
        """Test case for create_debit_memo_from_invoice

        Create a debit memo from an invoice  # noqa: E501
        """
        pass

    def test_create_taxation_items_for_debit_memo(self) -> None:
        """Test case for create_taxation_items_for_debit_memo

        Create taxation items for a debit memo  # noqa: E501
        """
        pass

    def test_delete_debit_memo(self) -> None:
        """Test case for delete_debit_memo

        Delete a debit memo  # noqa: E501
        """
        pass

    def test_email_debit_memo(self) -> None:
        """Test case for email_debit_memo

        Email a debit memo  # noqa: E501
        """
        pass

    def test_generate_debit_memo_pdf(self) -> None:
        """Test case for generate_debit_memo_pdf

        Generate a debit memo PDF file  # noqa: E501
        """
        pass

    def test_get_debit_memo(self) -> None:
        """Test case for get_debit_memo

        Retrieve a debit memo  # noqa: E501
        """
        pass

    def test_get_debit_memo_application_parts(self) -> None:
        """Test case for get_debit_memo_application_parts

        List all application parts of a debit memo  # noqa: E501
        """
        pass

    def test_get_debit_memo_item(self) -> None:
        """Test case for get_debit_memo_item

        Retrieve a debit memo item  # noqa: E501
        """
        pass

    def test_get_debit_memo_items(self) -> None:
        """Test case for get_debit_memo_items

        List debit memo items  # noqa: E501
        """
        pass

    def test_get_debit_memo_pdf_status(self) -> None:
        """Test case for get_debit_memo_pdf_status

        Retrieve PDF status of debit memos in a batch.  # noqa: E501
        """
        pass

    def test_get_debit_memos(self) -> None:
        """Test case for get_debit_memos

        List debit memos  # noqa: E501
        """
        pass

    def test_get_taxation_items_of_debit_memo_item(self) -> None:
        """Test case for get_taxation_items_of_debit_memo_item

        List all taxation items of a debit memo item  # noqa: E501
        """
        pass

    def test_post_async_debit_memo(self) -> None:
        """Test case for post_async_debit_memo

        Post a Debit Memo in async  # noqa: E501
        """
        pass

    def test_post_debit_memo(self) -> None:
        """Test case for post_debit_memo

        Post a debit memo  # noqa: E501
        """
        pass

    def test_unpost_debit_memo(self) -> None:
        """Test case for unpost_debit_memo

        Unpost a debit memo  # noqa: E501
        """
        pass

    def test_update_debit_memo(self) -> None:
        """Test case for update_debit_memo

        Update a debit memo  # noqa: E501
        """
        pass

    def test_update_debit_memos_due_dates(self) -> None:
        """Test case for update_debit_memos_due_dates

        Update due dates for debit memos  # noqa: E501
        """
        pass

    def test_upload_file_for_debit_memo(self) -> None:
        """Test case for upload_file_for_debit_memo

        Upload a file for a debit memo  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
