# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.zuora.api.custom_object_definitions_api import CustomObjectDefinitionsApi  # noqa: E501


class TestCustomObjectDefinitionsApi(unittest.TestCase):
    """CustomObjectDefinitionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomObjectDefinitionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_custom_object_definition_by_type(self) -> None:
        """Test case for delete_custom_object_definition_by_type

        Delete a custom object definition  # noqa: E501
        """
        pass

    def test_get_all_custom_object_definitions_in_namespace(self) -> None:
        """Test case for get_all_custom_object_definitions_in_namespace

        List custom object definitions  # noqa: E501
        """
        pass

    def test_get_custom_object_definition_by_type(self) -> None:
        """Test case for get_custom_object_definition_by_type

        Retrieve a custom object definition  # noqa: E501
        """
        pass

    def test_post_custom_object_definitions(self) -> None:
        """Test case for post_custom_object_definitions

        Create custom object definitions  # noqa: E501
        """
        pass

    def test_post_update_custom_object_definition(self) -> None:
        """Test case for post_update_custom_object_definition

        Update a custom object definition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
