# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.custom_object_all_fields_definition_all_of_created_date import CustomObjectAllFieldsDefinitionAllOfCreatedDate  # noqa: E501

class TestCustomObjectAllFieldsDefinitionAllOfCreatedDate(unittest.TestCase):
    """CustomObjectAllFieldsDefinitionAllOfCreatedDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomObjectAllFieldsDefinitionAllOfCreatedDate:
        """Test CustomObjectAllFieldsDefinitionAllOfCreatedDate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomObjectAllFieldsDefinitionAllOfCreatedDate`
        """
        model = CustomObjectAllFieldsDefinitionAllOfCreatedDate()  # noqa: E501
        if include_optional:
            return CustomObjectAllFieldsDefinitionAllOfCreatedDate(
                format = 'date-time',
                origin = 'system',
                type = 'string'
            )
        else:
            return CustomObjectAllFieldsDefinitionAllOfCreatedDate(
        )
        """

    def testCustomObjectAllFieldsDefinitionAllOfCreatedDate(self):
        """Test CustomObjectAllFieldsDefinitionAllOfCreatedDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
