# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.create_order_response_refund_status import CreateOrderResponseRefundStatus  # noqa: E501

class TestCreateOrderResponseRefundStatus(unittest.TestCase):
    """CreateOrderResponseRefundStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOrderResponseRefundStatus(self):
        """Test CreateOrderResponseRefundStatus"""
        # inst = CreateOrderResponseRefundStatus()

if __name__ == '__main__':
    unittest.main()
