# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.bulk_create_debit_memos_from_invoice_request import BulkCreateDebitMemosFromInvoiceRequest  # noqa: E501

class TestBulkCreateDebitMemosFromInvoiceRequest(unittest.TestCase):
    """BulkCreateDebitMemosFromInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkCreateDebitMemosFromInvoiceRequest:
        """Test BulkCreateDebitMemosFromInvoiceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkCreateDebitMemosFromInvoiceRequest`
        """
        model = BulkCreateDebitMemosFromInvoiceRequest()  # noqa: E501
        if include_optional:
            return BulkCreateDebitMemosFromInvoiceRequest(
                source_type = 'Invoice',
                memos = [
                    null
                    ]
            )
        else:
            return BulkCreateDebitMemosFromInvoiceRequest(
                source_type = 'Invoice',
        )
        """

    def testBulkCreateDebitMemosFromInvoiceRequest(self):
        """Test BulkCreateDebitMemosFromInvoiceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
