# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.payment_part import PaymentPart  # noqa: E501

class TestPaymentPart(unittest.TestCase):
    """PaymentPart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentPart:
        """Test PaymentPart
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentPart`
        """
        model = PaymentPart()  # noqa: E501
        if include_optional:
            return PaymentPart(
                amount = 1.337,
                created_by_id = '',
                created_date = '',
                debit_memo_id = '',
                id = '',
                invoice_id = '',
                updated_by_id = '',
                updated_date = '',
                organization_label = '',
                billing_document_owner_id = ''
            )
        else:
            return PaymentPart(
        )
        """

    def testPaymentPart(self):
        """Test PaymentPart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
