# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.taxation_items_data_response import TaxationItemsDataResponse  # noqa: E501

class TestTaxationItemsDataResponse(unittest.TestCase):
    """TaxationItemsDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxationItemsDataResponse:
        """Test TaxationItemsDataResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxationItemsDataResponse`
        """
        model = TaxationItemsDataResponse()  # noqa: E501
        if include_optional:
            return TaxationItemsDataResponse(
                process_id = '',
                request_id = '',
                reasons = [
                    {"code":"code","message":"message"}
                    ],
                success = True,
                data = [
                    com.zuora.models.data.data(
                        available_to_credit_amount = 1, 
                        balance = 1.337, 
                        credit_amount = 1.337, 
                        exempt_amount = 1.337, 
                        id = '', 
                        jurisdiction = '', 
                        location_code = '', 
                        name = '', 
                        payment_amount = 1.337, 
                        tax_amount = 1.337, 
                        tax_code = '', 
                        tax_code_description = '', 
                        tax_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        tax_rate = 1.337, 
                        tax_rate_description = '', 
                        tax_rate_type = 'Percentage', )
                    ],
                next_page = ''
            )
        else:
            return TaxationItemsDataResponse(
        )
        """

    def testTaxationItemsDataResponse(self):
        """Test TaxationItemsDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
