# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.refund_object_ns_fields import RefundObjectNSFields  # noqa: E501

class TestRefundObjectNSFields(unittest.TestCase):
    """RefundObjectNSFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundObjectNSFields:
        """Test RefundObjectNSFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundObjectNSFields`
        """
        model = RefundObjectNSFields()  # noqa: E501
        if include_optional:
            return RefundObjectNSFields(
                integration_id__ns = '',
                integration_status__ns = '',
                origin__ns = '',
                sync_date__ns = '',
                syncto_net_suite__ns = ''
            )
        else:
            return RefundObjectNSFields(
        )
        """

    def testRefundObjectNSFields(self):
        """Test RefundObjectNSFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
