# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.account_metrics import AccountMetrics  # noqa: E501

class TestAccountMetrics(unittest.TestCase):
    """AccountMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountMetrics:
        """Test AccountMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountMetrics`
        """
        model = AccountMetrics()  # noqa: E501
        if include_optional:
            return AccountMetrics(
                balance = 1.337,
                currency = '',
                contracted_mrr = 1.337,
                credit_balance = 1.337,
                reserved_payment_amount = 1.337,
                total_debit_memo_balance = 1.337,
                total_invoice_balance = 1.337,
                unapplied_credit_memo_amount = 1.337,
                unapplied_payment_amount = 1.337
            )
        else:
            return AccountMetrics(
        )
        """

    def testAccountMetrics(self):
        """Test AccountMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
