# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).  # noqa: E501

    OpenAPI spec version: 2023-10-24
    Contact: docs@zuora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zuora_sdk
from zuora_sdk.models.all_of_pricing_update_recurring_tiered import AllOfPricingUpdateRecurringTiered  # noqa: E501
from zuora_sdk.rest import ApiException


class TestAllOfPricingUpdateRecurringTiered(unittest.TestCase):
    """AllOfPricingUpdateRecurringTiered unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfPricingUpdateRecurringTiered(self):
        """Test AllOfPricingUpdateRecurringTiered"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zuora_sdk.models.all_of_pricing_update_recurring_tiered.AllOfPricingUpdateRecurringTiered()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
