# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/density.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/density.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\rDensityProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15gz/msgs/density.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\";\n\x07\x44\x65nsity\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0f\n\x07\x64\x65nsity\x18\x02 \x01(\x01\x42\x1c\n\x0b\x63om.gz.msgsB\rDensityProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_DENSITY = _descriptor.Descriptor(
  name='Density',
  full_name='gz.msgs.Density',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.Density.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='density', full_name='gz.msgs.Density.density', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=115,
)

_DENSITY.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Density'] = _DENSITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Density = _reflection.GeneratedProtocolMessageType('Density', (_message.Message,), {
  'DESCRIPTOR' : _DENSITY,
  '__module__' : 'gz.msgs.density_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.Density)
  })
_sym_db.RegisterMessage(Density)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
