# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/imu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import quaternion_pb2 as gz_dot_msgs_dot_quaternion__pb2
from gz.msgs import float_v_pb2 as gz_dot_msgs_dot_float__v__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/imu.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\tIMUProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11gz/msgs/imu.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x18gz/msgs/quaternion.proto\x1a\x15gz/msgs/float_v.proto\"\xe5\x02\n\x03IMU\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x13\n\x0b\x65ntity_name\x18\x02 \x01(\t\x12(\n\x0borientation\x18\x03 \x01(\x0b\x32\x13.gz.msgs.Quaternion\x12\x30\n\x16orientation_covariance\x18\x04 \x01(\x0b\x32\x10.gz.msgs.Float_V\x12+\n\x10\x61ngular_velocity\x18\x05 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x35\n\x1b\x61ngular_velocity_covariance\x18\x06 \x01(\x0b\x32\x10.gz.msgs.Float_V\x12.\n\x13linear_acceleration\x18\x07 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x38\n\x1elinear_acceleration_covariance\x18\x08 \x01(\x0b\x32\x10.gz.msgs.Float_VB\x18\n\x0b\x63om.gz.msgsB\tIMUProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,gz_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,gz_dot_msgs_dot_quaternion__pb2.DESCRIPTOR,gz_dot_msgs_dot_float__v__pb2.DESCRIPTOR,])




_IMU = _descriptor.Descriptor(
  name='IMU',
  full_name='gz.msgs.IMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.IMU.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='gz.msgs.IMU.entity_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='gz.msgs.IMU.orientation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation_covariance', full_name='gz.msgs.IMU.orientation_covariance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='gz.msgs.IMU.angular_velocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_velocity_covariance', full_name='gz.msgs.IMU.angular_velocity_covariance', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='gz.msgs.IMU.linear_acceleration', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_acceleration_covariance', full_name='gz.msgs.IMU.linear_acceleration_covariance', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=483,
)

_IMU.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_IMU.fields_by_name['orientation'].message_type = gz_dot_msgs_dot_quaternion__pb2._QUATERNION
_IMU.fields_by_name['orientation_covariance'].message_type = gz_dot_msgs_dot_float__v__pb2._FLOAT_V
_IMU.fields_by_name['angular_velocity'].message_type = gz_dot_msgs_dot_vector3d__pb2._VECTOR3D
_IMU.fields_by_name['angular_velocity_covariance'].message_type = gz_dot_msgs_dot_float__v__pb2._FLOAT_V
_IMU.fields_by_name['linear_acceleration'].message_type = gz_dot_msgs_dot_vector3d__pb2._VECTOR3D
_IMU.fields_by_name['linear_acceleration_covariance'].message_type = gz_dot_msgs_dot_float__v__pb2._FLOAT_V
DESCRIPTOR.message_types_by_name['IMU'] = _IMU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMU = _reflection.GeneratedProtocolMessageType('IMU', (_message.Message,), {
  'DESCRIPTOR' : _IMU,
  '__module__' : 'gz.msgs.imu_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.IMU)
  })
_sym_db.RegisterMessage(IMU)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
