# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/parameter_declarations.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import parameter_declaration_pb2 as gz_dot_msgs_dot_parameter__declaration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/parameter_declarations.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\033ParameterDeclarationsProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$gz/msgs/parameter_declarations.proto\x12\x07gz.msgs\x1a#gz/msgs/parameter_declaration.proto\"V\n\x15ParameterDeclarations\x12=\n\x16parameter_declarations\x18\x01 \x03(\x0b\x32\x1d.gz.msgs.ParameterDeclarationB*\n\x0b\x63om.gz.msgsB\x1bParameterDeclarationsProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_parameter__declaration__pb2.DESCRIPTOR,])




_PARAMETERDECLARATIONS = _descriptor.Descriptor(
  name='ParameterDeclarations',
  full_name='gz.msgs.ParameterDeclarations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter_declarations', full_name='gz.msgs.ParameterDeclarations.parameter_declarations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=172,
)

_PARAMETERDECLARATIONS.fields_by_name['parameter_declarations'].message_type = gz_dot_msgs_dot_parameter__declaration__pb2._PARAMETERDECLARATION
DESCRIPTOR.message_types_by_name['ParameterDeclarations'] = _PARAMETERDECLARATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParameterDeclarations = _reflection.GeneratedProtocolMessageType('ParameterDeclarations', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERDECLARATIONS,
  '__module__' : 'gz.msgs.parameter_declarations_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.ParameterDeclarations)
  })
_sym_db.RegisterMessage(ParameterDeclarations)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
