# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/pid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import double_pb2 as gz_dot_msgs_dot_double__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/pid.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\tPIDProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11gz/msgs/pid.proto\x12\x07gz.msgs\x1a\x14gz/msgs/double.proto\x1a\x14gz/msgs/header.proto\"\xc9\x02\n\x03PID\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12(\n\x0ftarget_optional\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0fp_gain_optional\x18\x03 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0fi_gain_optional\x18\x04 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0f\x64_gain_optional\x18\x05 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0ei_max_optional\x18\x06 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0ei_min_optional\x18\x07 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0elimit_optional\x18\x08 \x01(\x0b\x32\x0f.gz.msgs.DoubleB\x18\n\x0b\x63om.gz.msgsB\tPIDProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_double__pb2.DESCRIPTOR,gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_PID = _descriptor.Descriptor(
  name='PID',
  full_name='gz.msgs.PID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.PID.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_optional', full_name='gz.msgs.PID.target_optional', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p_gain_optional', full_name='gz.msgs.PID.p_gain_optional', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_gain_optional', full_name='gz.msgs.PID.i_gain_optional', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_gain_optional', full_name='gz.msgs.PID.d_gain_optional', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_max_optional', full_name='gz.msgs.PID.i_max_optional', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_min_optional', full_name='gz.msgs.PID.i_min_optional', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit_optional', full_name='gz.msgs.PID.limit_optional', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=404,
)

_PID.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_PID.fields_by_name['target_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['p_gain_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_gain_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['d_gain_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_max_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_min_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['limit_optional'].message_type = gz_dot_msgs_dot_double__pb2._DOUBLE
DESCRIPTOR.message_types_by_name['PID'] = _PID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PID = _reflection.GeneratedProtocolMessageType('PID', (_message.Message,), {
  'DESCRIPTOR' : _PID,
  '__module__' : 'gz.msgs.pid_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.PID)
  })
_sym_db.RegisterMessage(PID)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
