# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/propagation_particle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/propagation_particle.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\031PropagationParticleProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"gz/msgs/propagation_particle.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"b\n\x13PropagationParticle\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\x14\n\x0csignal_level\x18\x04 \x01(\x01\x42(\n\x0b\x63om.gz.msgsB\x19PropagationParticleProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_PROPAGATIONPARTICLE = _descriptor.Descriptor(
  name='PropagationParticle',
  full_name='gz.msgs.PropagationParticle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.PropagationParticle.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='gz.msgs.PropagationParticle.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='gz.msgs.PropagationParticle.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal_level', full_name='gz.msgs.PropagationParticle.signal_level', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=167,
)

_PROPAGATIONPARTICLE.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['PropagationParticle'] = _PROPAGATIONPARTICLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropagationParticle = _reflection.GeneratedProtocolMessageType('PropagationParticle', (_message.Message,), {
  'DESCRIPTOR' : _PROPAGATIONPARTICLE,
  '__module__' : 'gz.msgs.propagation_particle_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.PropagationParticle)
  })
_sym_db.RegisterMessage(PropagationParticle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
