# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/sim_event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import world_stats_pb2 as gz_dot_msgs_dot_world__stats__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/sim_event.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\016SimEventProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17gz/msgs/sim_event.proto\x12\x07gz.msgs\x1a\x19gz/msgs/world_stats.proto\x1a\x14gz/msgs/header.proto\"\x95\x01\n\x08SimEvent\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x32\n\x10world_statistics\x18\x05 \x01(\x0b\x32\x18.gz.msgs.WorldStatistics\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\tB\x1d\n\x0b\x63om.gz.msgsB\x0eSimEventProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_world__stats__pb2.DESCRIPTOR,gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_SIMEVENT = _descriptor.Descriptor(
  name='SimEvent',
  full_name='gz.msgs.SimEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.SimEvent.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='gz.msgs.SimEvent.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='gz.msgs.SimEvent.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='gz.msgs.SimEvent.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_statistics', full_name='gz.msgs.SimEvent.world_statistics', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='gz.msgs.SimEvent.data', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=235,
)

_SIMEVENT.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_SIMEVENT.fields_by_name['world_statistics'].message_type = gz_dot_msgs_dot_world__stats__pb2._WORLDSTATISTICS
DESCRIPTOR.message_types_by_name['SimEvent'] = _SIMEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimEvent = _reflection.GeneratedProtocolMessageType('SimEvent', (_message.Message,), {
  'DESCRIPTOR' : _SIMEVENT,
  '__module__' : 'gz.msgs.sim_event_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.SimEvent)
  })
_sym_db.RegisterMessage(SimEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
