# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/sonar.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/sonar.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\013SonarProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13gz/msgs/sonar.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xd5\x01\n\x05Sonar\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\r\n\x05\x66rame\x18\x02 \x01(\t\x12!\n\nworld_pose\x18\x03 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x11\n\trange_min\x18\x04 \x01(\x01\x12\x11\n\trange_max\x18\x05 \x01(\x01\x12\x0e\n\x06radius\x18\x06 \x01(\x01\x12\r\n\x05range\x18\x07 \x01(\x01\x12\x10\n\x08geometry\x18\x08 \x01(\t\x12\"\n\x07\x63ontact\x18\t \x01(\x0b\x32\x11.gz.msgs.Vector3dB\x1a\n\x0b\x63om.gz.msgsB\x0bSonarProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_pose__pb2.DESCRIPTOR,gz_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_SONAR = _descriptor.Descriptor(
  name='Sonar',
  full_name='gz.msgs.Sonar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.Sonar.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='gz.msgs.Sonar.frame', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_pose', full_name='gz.msgs.Sonar.world_pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range_min', full_name='gz.msgs.Sonar.range_min', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range_max', full_name='gz.msgs.Sonar.range_max', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='radius', full_name='gz.msgs.Sonar.radius', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='gz.msgs.Sonar.range', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='gz.msgs.Sonar.geometry', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contact', full_name='gz.msgs.Sonar.contact', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=312,
)

_SONAR.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_SONAR.fields_by_name['world_pose'].message_type = gz_dot_msgs_dot_pose__pb2._POSE
_SONAR.fields_by_name['contact'].message_type = gz_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Sonar'] = _SONAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sonar = _reflection.GeneratedProtocolMessageType('Sonar', (_message.Message,), {
  'DESCRIPTOR' : _SONAR,
  '__module__' : 'gz.msgs.sonar_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.Sonar)
  })
_sym_db.RegisterMessage(Sonar)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
