# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/twist_with_covariance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import float_v_pb2 as gz_dot_msgs_dot_float__v__pb2
from gz.msgs import twist_pb2 as gz_dot_msgs_dot_twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/twist_with_covariance.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\031TwistWithCovarianceProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#gz/msgs/twist_with_covariance.proto\x12\x07gz.msgs\x1a\x15gz/msgs/float_v.proto\x1a\x13gz/msgs/twist.proto\"Z\n\x13TwistWithCovariance\x12\x1d\n\x05twist\x18\x01 \x01(\x0b\x32\x0e.gz.msgs.Twist\x12$\n\ncovariance\x18\x02 \x01(\x0b\x32\x10.gz.msgs.Float_VB(\n\x0b\x63om.gz.msgsB\x19TwistWithCovarianceProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_float__v__pb2.DESCRIPTOR,gz_dot_msgs_dot_twist__pb2.DESCRIPTOR,])




_TWISTWITHCOVARIANCE = _descriptor.Descriptor(
  name='TwistWithCovariance',
  full_name='gz.msgs.TwistWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='twist', full_name='gz.msgs.TwistWithCovariance.twist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='gz.msgs.TwistWithCovariance.covariance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=182,
)

_TWISTWITHCOVARIANCE.fields_by_name['twist'].message_type = gz_dot_msgs_dot_twist__pb2._TWIST
_TWISTWITHCOVARIANCE.fields_by_name['covariance'].message_type = gz_dot_msgs_dot_float__v__pb2._FLOAT_V
DESCRIPTOR.message_types_by_name['TwistWithCovariance'] = _TWISTWITHCOVARIANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwistWithCovariance = _reflection.GeneratedProtocolMessageType('TwistWithCovariance', (_message.Message,), {
  'DESCRIPTOR' : _TWISTWITHCOVARIANCE,
  '__module__' : 'gz.msgs.twist_with_covariance_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.TwistWithCovariance)
  })
_sym_db.RegisterMessage(TwistWithCovariance)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
