# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/undo_redo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/undo_redo.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\016UndoRedoProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17gz/msgs/undo_redo.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"E\n\x08UndoRedo\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04undo\x18\x02 \x01(\x08\x12\n\n\x02id\x18\x03 \x01(\rB\x1d\n\x0b\x63om.gz.msgsB\x0eUndoRedoProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_UNDOREDO = _descriptor.Descriptor(
  name='UndoRedo',
  full_name='gz.msgs.UndoRedo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.UndoRedo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='undo', full_name='gz.msgs.UndoRedo.undo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='gz.msgs.UndoRedo.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=127,
)

_UNDOREDO.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['UndoRedo'] = _UNDOREDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UndoRedo = _reflection.GeneratedProtocolMessageType('UndoRedo', (_message.Message,), {
  'DESCRIPTOR' : _UNDOREDO,
  '__module__' : 'gz.msgs.undo_redo_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.UndoRedo)
  })
_sym_db.RegisterMessage(UndoRedo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
