# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.models.sign_developer_typed_data200_response import SignDeveloperTypedData200Response  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException

class TestSignDeveloperTypedData200Response(unittest.TestCase):
    """SignDeveloperTypedData200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SignDeveloperTypedData200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignDeveloperTypedData200Response`
        """
        model = circle.web3.developer_controlled_wallets.models.sign_developer_typed_data200_response.SignDeveloperTypedData200Response()  # noqa: E501
        if include_optional :
            return SignDeveloperTypedData200Response(
                data = circle.web3.developer_controlled_wallets.models.sign_typed_data_for_developer_response.SignTypedDataForDeveloperResponse(
                    signature = '0x977c17f82d8b042b67b09d0e61e7d324f050cb000c17a08...', )
            )
        else :
            return SignDeveloperTypedData200Response(
        )
        """

    def testSignDeveloperTypedData200Response(self):
        """Test SignDeveloperTypedData200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
