# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.order_line_item_type import OrderLineItemType  # noqa: E501

class TestOrderLineItemType(unittest.TestCase):
    """OrderLineItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderLineItemType(self):
        """Test OrderLineItemType"""
        # inst = OrderLineItemType()

if __name__ == '__main__':
    unittest.main()
