# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.service_provider_response import ServiceProviderResponse  # noqa: E501

class TestServiceProviderResponse(unittest.TestCase):
    """ServiceProviderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceProviderResponse:
        """Test ServiceProviderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceProviderResponse`
        """
        model = ServiceProviderResponse()  # noqa: E501
        if include_optional:
            return ServiceProviderResponse(
                process_id = '',
                request_id = '',
                reasons = [
                    {"code":"code","message":"message"}
                    ],
                success = True,
                id = '',
                name = '',
                test = True,
                provider = 'Sovos',
                service_provider_number = '',
                company_identifier = '',
                api_key = '',
                client_certificate = '',
                client_certificate_type = ''
            )
        else:
            return ServiceProviderResponse(
        )
        """

    def testServiceProviderResponse(self):
        """Test ServiceProviderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
