# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.recurring_volume_pricing_override import RecurringVolumePricingOverride  # noqa: E501

class TestRecurringVolumePricingOverride(unittest.TestCase):
    """RecurringVolumePricingOverride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecurringVolumePricingOverride:
        """Test RecurringVolumePricingOverride
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecurringVolumePricingOverride`
        """
        model = RecurringVolumePricingOverride()  # noqa: E501
        if include_optional:
            return RecurringVolumePricingOverride(
                price_change_option = 'NoChange',
                price_increase_percentage = -100,
                list_price_base = 'Per_Billing_Period',
                quantity = 0,
                specific_list_price_base = 1,
                tiers = [
                    {"endingUnit":2.027123023002322,"price":4.145608029883936,"priceFormat":"FlatFee","startingUnit":7.386281948385884,"tier":1}
                    ],
                uom = ''
            )
        else:
            return RecurringVolumePricingOverride(
        )
        """

    def testRecurringVolumePricingOverride(self):
        """Test RecurringVolumePricingOverride"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
