# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.create_product_request import CreateProductRequest  # noqa: E501

class TestCreateProductRequest(unittest.TestCase):
    """CreateProductRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProductRequest:
        """Test CreateProductRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProductRequest`
        """
        model = CreateProductRequest()  # noqa: E501
        if include_optional:
            return CreateProductRequest(
                integration_id__ns = '',
                integration_status__ns = '',
                item_type__ns = 'Inventory',
                sync_date__ns = '',
                sku = '',
                name = '',
                product_number = '',
                category = 'Base Products',
                description = '',
                effective_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                effective_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                allow_feature_changes = True
            )
        else:
            return CreateProductRequest(
                name = '',
                effective_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                effective_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testCreateProductRequest(self):
        """Test CreateProductRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
