# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.create_debit_memos_from_invoice_request import CreateDebitMemosFromInvoiceRequest  # noqa: E501

class TestCreateDebitMemosFromInvoiceRequest(unittest.TestCase):
    """CreateDebitMemosFromInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDebitMemosFromInvoiceRequest:
        """Test CreateDebitMemosFromInvoiceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDebitMemosFromInvoiceRequest`
        """
        model = CreateDebitMemosFromInvoiceRequest()  # noqa: E501
        if include_optional:
            return CreateDebitMemosFromInvoiceRequest(
                auto_pay = True,
                auto_post = True,
                comment = '',
                effective_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                invoice_id = '',
                items = [
                    { }
                    ],
                reason_code = '',
                tax_auto_calculation = True,
                integration_id__ns = '',
                integration_status__ns = '',
                sync_date__ns = ''
            )
        else:
            return CreateDebitMemosFromInvoiceRequest(
        )
        """

    def testCreateDebitMemosFromInvoiceRequest(self):
        """Test CreateDebitMemosFromInvoiceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
