# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.payment_method_response_google_pay import PaymentMethodResponseGooglePay  # noqa: E501

class TestPaymentMethodResponseGooglePay(unittest.TestCase):
    """PaymentMethodResponseGooglePay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodResponseGooglePay:
        """Test PaymentMethodResponseGooglePay
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodResponseGooglePay`
        """
        model = PaymentMethodResponseGooglePay()  # noqa: E501
        if include_optional:
            return PaymentMethodResponseGooglePay(
                google_bin = '',
                google_card_number = '',
                google_card_type = '',
                google_expiry_date = '',
                google_gateway_token = ''
            )
        else:
            return PaymentMethodResponseGooglePay(
        )
        """

    def testPaymentMethodResponseGooglePay(self):
        """Test PaymentMethodResponseGooglePay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
