# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.delete_batch_query_job_response import DeleteBatchQueryJobResponse  # noqa: E501

class TestDeleteBatchQueryJobResponse(unittest.TestCase):
    """DeleteBatchQueryJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteBatchQueryJobResponse:
        """Test DeleteBatchQueryJobResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteBatchQueryJobResponse`
        """
        model = DeleteBatchQueryJobResponse()  # noqa: E501
        if include_optional:
            return DeleteBatchQueryJobResponse(
                batches = [
                    com.zuora.models.batch.batch(
                        batch_id = '', 
                        batch_type = 'zoql', 
                        file_id = '', 
                        message = '', 
                        name = '', 
                        query = '', 
                        record_count = '', 
                        segments = [
                            ''
                            ], 
                        status = 'submitted', )
                    ],
                format = 'CSV',
                id = '',
                name = '',
                encrypted = 'pgp',
                use_last_completed_job_queries = True,
                offset = 1.337,
                partner = '',
                status = 'submitted',
                localized_status = 'submitted',
                version = 1.337,
                error_code = '',
                message = ''
            )
        else:
            return DeleteBatchQueryJobResponse(
        )
        """

    def testDeleteBatchQueryJobResponse(self):
        """Test DeleteBatchQueryJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
