# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.create_invoice_schedule_request import CreateInvoiceScheduleRequest  # noqa: E501

class TestCreateInvoiceScheduleRequest(unittest.TestCase):
    """CreateInvoiceScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInvoiceScheduleRequest:
        """Test CreateInvoiceScheduleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInvoiceScheduleRequest`
        """
        model = CreateInvoiceScheduleRequest()  # noqa: E501
        if include_optional:
            return CreateInvoiceScheduleRequest(
                account_key = '',
                additional_subscriptions_to_bill = [
                    ''
                    ],
                invoice_separately = True,
                notes = '',
                orders = [
                    ''
                    ],
                schedule_items = [
                    { }
                    ],
                specific_subscriptions = [
                    com.zuora.models.specific_subscriptions.specificSubscriptions(
                        order_key = '', 
                        subscription_key = '', 
                        charge_numbers = [
                            ''
                            ], )
                    ]
            )
        else:
            return CreateInvoiceScheduleRequest(
        )
        """

    def testCreateInvoiceScheduleRequest(self):
        """Test CreateInvoiceScheduleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
