# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from com.zuora.models.put_public_notification_definition_request import PutPublicNotificationDefinitionRequest  # noqa: E501

class TestPutPublicNotificationDefinitionRequest(unittest.TestCase):
    """PutPublicNotificationDefinitionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutPublicNotificationDefinitionRequest:
        """Test PutPublicNotificationDefinitionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutPublicNotificationDefinitionRequest`
        """
        model = PutPublicNotificationDefinitionRequest()  # noqa: E501
        if include_optional:
            return PutPublicNotificationDefinitionRequest(
                active = True,
                associated_account = '',
                callout = com.zuora.models.put_public_notification_definition_request_callout.PutPublicNotificationDefinitionRequest_callout(
                    active = True, 
                    callout_auth = com.zuora.models.callout_auth.CalloutAuth(
                        domain = '', 
                        password = '', 
                        preemptive = True, 
                        username = '', ), 
                    callout_baseurl = 'https://***', 
                    callout_params = {
                        'key' : ''
                        }, 
                    callout_retry = True, 
                    description = '', 
                    http_method = 'POST', 
                    name = '', 
                    required_auth = True, ),
                callout_active = True,
                communication_profile_id = '',
                description = '',
                email_active = True,
                email_template_id = '',
                filter_rule = com.zuora.models.put_public_notification_definition_request_filter_rule.PutPublicNotificationDefinitionRequest_filterRule(
                    condition = 'Account.Balance >= _VIP_BALANCE_AMOUNT && Account.Status == _ACCOUNT_STATUS', 
                    description = '', 
                    parameters = {
                        'key' : com.zuora.models.parameter.parameter(
                            description = '', 
                            display_name = '', 
                            options = [
                                ''
                                ], 
                            value_type = 'STRING', )
                        }, ),
                filter_rule_params = {
                    'key' : ''
                    },
                name = ''
            )
        else:
            return PutPublicNotificationDefinitionRequest(
        )
        """

    def testPutPublicNotificationDefinitionRequest(self):
        """Test PutPublicNotificationDefinitionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
