
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-17T12:29:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "50731654f958837e6e9598342fbd105994cc9c11",
 "version": "1.8.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
