from .content import Content

class Badge(Content):
	def __init__(self, badge_data: dict) -> None: ...
	async def name(self) -> str: ...
	async def description(self, in_html: bool) -> str: ...
	async def having_count(self) -> int: ...
	async def preciousness(self) -> int: ...