import pytest
from rusty_email_validator import validate


@pytest.mark.parametrize(
    "email,expected",
    [
        ("email@here.com", True),
        ("weirder-email@here.and.there.com", True),
        (r"!def!xyz%abc@example.com", True),
        ("email@[127.0.0.1]", True),
        ("email@[2001:dB8::1]", True),
        ("email@[2001:dB8:0:0:0:0:0:1]", True),
        ("email@[::fffF:127.0.0.1]", True),
        ("example@valid-----hyphens.com", True),
        ("example@valid-with-hyphens.com", True),
        ("test@domain.with.idn.tld.उदाहरण.परीक्षा", True),
        (r'"test@test"@example.com', False),
        ("a@atm.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("a@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.atm", True),
        (
            "a@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbb.atm",
            True,
        ),
        (
            "a@atm.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            False,
        ),
        ("", False),
        ("abc", False),
        ("abc@", False),
        ("abc@bar", True),
        ("a @x.cz", False),
        ("abc@.com", False),
        ("something@@somewhere.com", False),
        ("email@127.0.0.1", True),
        ("email@[127.0.0.256]", False),
        ("email@[2001:db8::12345]", False),
        ("email@[2001:db8:0:0:0:0:1]", False),
        ("email@[::ffff:127.0.0.256]", False),
        ("example@invalid-.com", False),
        ("example@-invalid.com", False),
        ("example@invalid.com-", False),
        ("example@inv-.alid-.com", False),
        ("example@inv-.-alid.com", False),
        (r'test@example.com\n\n<script src="x.js">', False),
        (r'"\\011"@here.com', False),
        (r'"\\012"@here.com', False),
        ("trailingdot@shouldfail.com.", False),
        ("a@b.com\n", False),
        ("a\n@b.com", False),
        (r'"test@test"\n@example.com', False),
        ("a@[127.0.0.1]\n", False),
        ("John.Doe@exam_ple.com", False),
    ],
    ids=[
        "validate_email_email@here.com_should_be_true",
        "validate_email_weirder-email@here.and.there.com_should_be_true",
        "validate_email_!def!xyz%abc@example.com_should_be_true",
        "validate_email_email@[127.0.0.1]_should_be_true",
        "validate_email_email@[2001:dB8::1]_should_be_true",
        "validate_email_email@[2001:dB8:0:0:0:0:0:1]_should_be_true",
        "validate_email_email@[::fffF:127.0.0.1]_should_be_true",
        "validate_email_example@valid-----hyphens.com_should_be_true",
        "validate_email_example@valid-with-hyphens.com_should_be_true",
        "validate_email_test@domain.with.idn.tld.उदाहरण.परीक्षा_should_be_true",
        "validate_email_\"test@test\"@example.com_should_be_false",
        "validate_email_a@atm.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_should_be_true",
        "validate_email_a@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.atm_should_be_true",
        "validate_email_a@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbb.atm_should_be_true",
        "validate_email_a@atm.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_should_be_false",
        "validate_email_empty_string_should_be_false",
        "validate_email_abc_should_be_false",
        "validate_email_abc@_should_be_false",
        "validate_email_abc@bar_should_be_true",
        "validate_email_a @x.cz_should_be_false",
        "validate_email_abc@.com_should_be_false",
        "validate_email_something@@somewhere.com_should_be_false",
        "validate_email_email@127.0.0.1_should_be_true",
        "validate_email_email@[127.0.0.256]_should_be_false",
        "validate_email_email@[2001:db8::12345]_should_be_false",
        "validate_email_email@[2001:db8:0:0:0:0:1]_should_be_false",
        "validate_email_email@[::ffff:127.0.0.256]_should_be_false",
        "validate_email_example@invalid-.com_should_be_false",
        "validate_email_example@-invalid.com_should_be_false",
        "validate_email_example@invalid.com-_should_be_false",
        "validate_email_example@inv-.alid-.com_should_be_false",
        "validate_email_example@inv-.-alid.com_should_be_false",
        "validate_email_test@example.com\\n\\n<script src=\"x.js\">_should_be_false",
        "validate_email_\"\\\\011\"@here.com_should_be_false",
        "validate_email_\"\\\\012\"@here.com_should_be_false",
        "validate_email_trailingdot@shouldfail.com._should_be_false",
        "validate_email_a@b.com\\n_should_be_false",
        "validate_email_a\\n@b.com_should_be_false",
        "validate_email_\"test@test\"\\n@example.com_should_be_false",
        "validate_email_a@[127.0.0.1]\\n_should_be_false",
        "validate_email_John.Doe@exam_ple.com_should_be_false",
    ]
)
def test_validate_email(email: str, expected: bool) -> None:
    assert validate(email) == expected