from typing import Literal

from .utilities import format_message as format_message

class PrecisionTimer:
    def __init__(self, precision: Literal["ns", "us", "ms", "s"] = "us") -> None: ...
    @property
    def elapsed(self) -> int: ...
    @property
    def precision(self) -> str: ...
    @property
    def supported_precisions(self) -> tuple: ...
    def reset(self) -> None: ...
    def delay_noblock(self, delay: int, *, allow_sleep: bool = False) -> None: ...
    def delay_block(self, delay: int, *, allow_sleep: bool = False) -> None: ...
    def set_precision(self, precision: Literal["ns", "us", "ms", "s"]) -> None: ...
