# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class RevRecTrigger(str, Enum):
    """
    Specifies the revenue recognition trigger condition.
    """

    """
    allowed enum values
    """
    CONTRACTEFFECTIVEDATE = 'ContractEffectiveDate'
    SERVICEACTIVATIONDATE = 'ServiceActivationDate'
    CUSTOMERACCEPTANCEDATE = 'CustomerAcceptanceDate'

    @classmethod
    def from_json(cls, json_str: str) -> RevRecTrigger:
        """Create an instance of RevRecTrigger from a JSON string"""
        return RevRecTrigger(json.loads(json_str))


