# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TaxExemptStatus(str, Enum):
    """
    Status of the account tax exemption. Applicable if you use Zuora Tax or Connect tax engines. Required if you use Zuora Tax.  
    """

    """
    allowed enum values
    """
    NO = 'No'
    YES = 'Yes'
    PENDINGVERIFICATION = 'PendingVerification'

    @classmethod
    def from_json(cls, json_str: str) -> TaxExemptStatus:
        """Create an instance of TaxExemptStatus from a JSON string"""
        return TaxExemptStatus(json.loads(json_str))


