# Copyright 2024 OpenSynergy Indonesia
# Copyright 2024 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Consolidated Financial Statement Worksheet",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_date_duration_mixin",
        "ssi_financial_accounting",
        "ssi_account_account_m2o_configurator_mixin",
        "ssi_account_journal_m2o_configurator_mixin",
        "ssi_res_partner_m2o_configurator_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_company_currency_mixin",
    ],
    "data": [
        "security/ir_module_category/subsidiary_trial_balance.xml",
        "security/ir_module_category/fs_consolidation_ws.xml",
        "security/ir_module_category/elimination_entry.xml",
        "security/ir_module_category/subsidiary_tb_adjustment_entry.xml",
        "security/res_group/res_group_data.xml",
        "security/res_group/subsidiary_trial_balance.xml",
        "security/res_group/fs_consolidation_ws.xml",
        "security/res_group/elimination_entry.xml",
        "security/res_group/subsidiary_tb_adjustment_entry.xml",
        "security/res_group/subsidiary_trial_balance.xml",
        "security/res_group/fs_consolidation_ws.xml",
        "security/res_group/elimination_entry.xml",
        "security/res_group/subsidiary_tb_adjustment_entry.xml",
        "security/ir_rule/subsidiary_trial_balance.xml",
        "security/ir_rule/fs_consolidation_ws.xml",
        "security/ir_rule/elimination_entry.xml",
        "security/ir_rule/subsidiary_tb_adjustment_entry.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence/subsidiary_trial_balance.xml",
        "data/ir_sequence/fs_consolidation_ws.xml",
        "data/ir_sequence/elimination_entry.xml",
        "data/ir_sequence/subsidiary_tb_adjustment_entry.xml",
        "data/sequence_template/subsidiary_trial_balance.xml",
        "data/sequence_template/fs_consolidation_ws.xml",
        "data/sequence_template/elimination_entry.xml",
        "data/sequence_template/subsidiary_tb_adjustment_entry.xml",
        "data/approval_template/subsidiary_trial_balance.xml",
        "data/approval_template/fs_consolidation_ws.xml",
        "data/approval_template/elimination_entry.xml",
        "data/approval_template/subsidiary_tb_adjustment_entry.xml",
        "data/policy_template/subsidiary_trial_balance.xml",
        "data/policy_template/fs_consolidation_ws.xml",
        "data/policy_template/elimination_entry.xml",
        "data/policy_template/subsidiary_tb_adjustment_entry.xml",
        "menu.xml",
        "views/fs_consolidation_ws_type_views.xml",
        "views/fs_consolidation_ws_views.xml",
        "views/subsidiary_trial_balance_views.xml",
        "views/elimination_entry_views.xml",
        "views/subsidiary_tb_adjustmeny_entry_views.xml",
    ],
    "demo": [],
    "images": [],
}
