# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).  # noqa: E501

    OpenAPI spec version: 2023-10-24
    Contact: docs@zuora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zuora_sdk
from zuora_sdk.models.get_debit_memo_tax_item import GetDebitMemoTaxItem  # noqa: E501
from zuora_sdk.rest import ApiException


class TestGetDebitMemoTaxItem(unittest.TestCase):
    """GetDebitMemoTaxItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDebitMemoTaxItem(self):
        """Test GetDebitMemoTaxItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zuora_sdk.models.get_debit_memo_tax_item.GetDebitMemoTaxItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
