# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/model_v.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import model_pb2 as gz_dot_msgs_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/model_v.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\014ModelVProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15gz/msgs/model_v.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x13gz/msgs/model.proto\"J\n\x07Model_V\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1e\n\x06models\x18\x02 \x03(\x0b\x32\x0e.gz.msgs.ModelB\x1b\n\x0b\x63om.gz.msgsB\x0cModelVProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,gz_dot_msgs_dot_model__pb2.DESCRIPTOR,])




_MODEL_V = _descriptor.Descriptor(
  name='Model_V',
  full_name='gz.msgs.Model_V',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.Model_V.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models', full_name='gz.msgs.Model_V.models', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=151,
)

_MODEL_V.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_MODEL_V.fields_by_name['models'].message_type = gz_dot_msgs_dot_model__pb2._MODEL
DESCRIPTOR.message_types_by_name['Model_V'] = _MODEL_V
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model_V = _reflection.GeneratedProtocolMessageType('Model_V', (_message.Message,), {
  'DESCRIPTOR' : _MODEL_V,
  '__module__' : 'gz.msgs.model_v_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.Model_V)
  })
_sym_db.RegisterMessage(Model_V)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
