# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/sensor_noise.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/sensor_noise.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\006Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1agz/msgs/sensor_noise.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xac\x02\n\x0bSensorNoise\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.gz.msgs.SensorNoise.Type\x12\x0c\n\x04mean\x18\x03 \x01(\x01\x12\x0e\n\x06stddev\x18\x04 \x01(\x01\x12\x11\n\tbias_mean\x18\x05 \x01(\x01\x12\x13\n\x0b\x62ias_stddev\x18\x06 \x01(\x01\x12\x11\n\tprecision\x18\x07 \x01(\x01\x12\x1b\n\x13\x64ynamic_bias_stddev\x18\x08 \x01(\x01\x12%\n\x1d\x64ynamic_bias_correlation_time\x18\t \x01(\x01\"6\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08GAUSSIAN\x10\x02\x12\x16\n\x12GAUSSIAN_QUANTIZED\x10\x03\x42\x15\n\x0b\x63om.gz.msgsB\x06Protosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])



_SENSORNOISE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='gz.msgs.SensorNoise.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAUSSIAN', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAUSSIAN_QUANTIZED', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=308,
  serialized_end=362,
)
_sym_db.RegisterEnumDescriptor(_SENSORNOISE_TYPE)


_SENSORNOISE = _descriptor.Descriptor(
  name='SensorNoise',
  full_name='gz.msgs.SensorNoise',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.SensorNoise.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='gz.msgs.SensorNoise.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='gz.msgs.SensorNoise.mean', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stddev', full_name='gz.msgs.SensorNoise.stddev', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bias_mean', full_name='gz.msgs.SensorNoise.bias_mean', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bias_stddev', full_name='gz.msgs.SensorNoise.bias_stddev', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precision', full_name='gz.msgs.SensorNoise.precision', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dynamic_bias_stddev', full_name='gz.msgs.SensorNoise.dynamic_bias_stddev', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dynamic_bias_correlation_time', full_name='gz.msgs.SensorNoise.dynamic_bias_correlation_time', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORNOISE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=362,
)

_SENSORNOISE.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_SENSORNOISE.fields_by_name['type'].enum_type = _SENSORNOISE_TYPE
_SENSORNOISE_TYPE.containing_type = _SENSORNOISE
DESCRIPTOR.message_types_by_name['SensorNoise'] = _SENSORNOISE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorNoise = _reflection.GeneratedProtocolMessageType('SensorNoise', (_message.Message,), {
  'DESCRIPTOR' : _SENSORNOISE,
  '__module__' : 'gz.msgs.sensor_noise_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.SensorNoise)
  })
_sym_db.RegisterMessage(SensorNoise)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
