# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/sky.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gz/msgs/sky.proto',
  package='gz.msgs',
  syntax='proto3',
  serialized_options=b'\n\013com.gz.msgsB\tSkyProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11gz/msgs/sky.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/header.proto\"\xe8\x01\n\x03Sky\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12\x0f\n\x07sunrise\x18\x03 \x01(\x01\x12\x0e\n\x06sunset\x18\x04 \x01(\x01\x12\x12\n\nwind_speed\x18\x05 \x01(\x01\x12\x16\n\x0ewind_direction\x18\x06 \x01(\x01\x12%\n\rcloud_ambient\x18\x07 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x10\n\x08humidity\x18\x08 \x01(\x01\x12\x17\n\x0fmean_cloud_size\x18\t \x01(\x01\x12\x13\n\x0b\x63ubemap_uri\x18\n \x01(\tB\x18\n\x0b\x63om.gz.msgsB\tSkyProtosb\x06proto3'
  ,
  dependencies=[gz_dot_msgs_dot_color__pb2.DESCRIPTOR,gz_dot_msgs_dot_header__pb2.DESCRIPTOR,])




_SKY = _descriptor.Descriptor(
  name='Sky',
  full_name='gz.msgs.Sky',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gz.msgs.Sky.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='gz.msgs.Sky.time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sunrise', full_name='gz.msgs.Sky.sunrise', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sunset', full_name='gz.msgs.Sky.sunset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='gz.msgs.Sky.wind_speed', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='gz.msgs.Sky.wind_direction', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_ambient', full_name='gz.msgs.Sky.cloud_ambient', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='gz.msgs.Sky.humidity', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_cloud_size', full_name='gz.msgs.Sky.mean_cloud_size', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cubemap_uri', full_name='gz.msgs.Sky.cubemap_uri', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=306,
)

_SKY.fields_by_name['header'].message_type = gz_dot_msgs_dot_header__pb2._HEADER
_SKY.fields_by_name['cloud_ambient'].message_type = gz_dot_msgs_dot_color__pb2._COLOR
DESCRIPTOR.message_types_by_name['Sky'] = _SKY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sky = _reflection.GeneratedProtocolMessageType('Sky', (_message.Message,), {
  'DESCRIPTOR' : _SKY,
  '__module__' : 'gz.msgs.sky_pb2'
  # @@protoc_insertion_point(class_scope:gz.msgs.Sky)
  })
_sym_db.RegisterMessage(Sky)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
