from high_precision_timer.precision_timer import PrecisionTimer
from high_precision_timer.precision_timer_ext import CPrecisionTimer as CPrecisionTimer

global_counter: int
end_flag: bool

def update_global_counter() -> None: ...
def verify_delay_method(
    timer: PrecisionTimer, precision: str, delay: int, *, allow_sleep: bool = False, blocking: bool = False
) -> None: ...
def verify_interval_method(timer: PrecisionTimer, precision: str, interval: int) -> None: ...
def test_initialization_and_precision_control() -> None: ...
def test_initialization_and_precision_control_errors() -> None: ...
def test_elapsed_property() -> None: ...
def test_interval_timing(precision: str) -> None: ...
def test_delay_timing(precision: str, allow_sleep: bool, blocking: bool) -> None: ...
def test_threaded_delay() -> None: ...
