# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).  # noqa: E501

    OpenAPI spec version: 2023-10-24
    Contact: docs@zuora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zuora_sdk
from zuora_sdk.api.refunds_api import RefundsApi  # noqa: E501
from zuora_sdk.rest import ApiException


class TestRefundsApi(unittest.TestCase):
    """RefundsApi unit test stubs"""

    def setUp(self):
        self.api = RefundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_refund(self):
        """Test case for cancel_refund

        Cancel a refund  # noqa: E501
        """
        pass

    def test_delete_refund(self):
        """Test case for delete_refund

        Delete a refund  # noqa: E501
        """
        pass

    def test_get_refund(self):
        """Test case for get_refund

        Retrieve a refund  # noqa: E501
        """
        pass

    def test_get_refund_item_part(self):
        """Test case for get_refund_item_part

        Retrieve a refund part item  # noqa: E501
        """
        pass

    def test_get_refund_item_parts(self):
        """Test case for get_refund_item_parts

        List all refund part items  # noqa: E501
        """
        pass

    def test_get_refund_part(self):
        """Test case for get_refund_part

        Retrieve a refund part  # noqa: E501
        """
        pass

    def test_get_refund_parts(self):
        """Test case for get_refund_parts

        List all parts of a refund  # noqa: E501
        """
        pass

    def test_get_refunds(self):
        """Test case for get_refunds

        List refunds  # noqa: E501
        """
        pass

    def test_update_refund(self):
        """Test case for update_refund

        Update a refund  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
