from collections.abc import Callable
from typing import NoReturn, List, Any

__all__: List[str] = ["get_type_name", "_force_args_as_path", "_raise_if_not_path_type"]

def get_type_name(object: Any) -> bool: ...
def _force_args_as_path(absolute: bool = True) -> Callable[..., Any]: ...
def _raise_if_not_path_type(object: Any) -> None | NoReturn: ...