from .content import Content
from typing import Optional

class User(Content):
	def __init__(self, username: str) -> None: ...
	async def __get_user(self) -> dict: ...
	async def username(self) -> str: ...
	async def name(self) -> Optional[str]: ...
	async def avatar(self, size: int = 400) -> str: ...
	async def bio(self) -> Optional[str]: ...
	async def website(self) -> Optional[str]: ...
	async def location(self) -> Optional[str]: ...
	async def title(self) -> Optional[str]: ...
	async def trust_level(self) -> int: ...
	async def badges(self) -> list: ...
	async def pinned_badges(self) -> list: ...
	async def is_banned(self) -> bool: ...
	async def invited_by(self) -> Optional["User"]: ...
	async def card_background(self) -> Optional[str]: ...
	async def profile_background(self) -> Optional[str]: ...
	async def featured_topic(self) -> Optional[Topic]: ...