/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
N_LIB_PRIVATE NIM_CONST tyArray__vEOa9c5qaE9ajWxR5R4zwfQg lookup__pureZbitops_u285 = {((NU8)0),
((NU8)1),
((NU8)28),
((NU8)2),
((NU8)29),
((NU8)14),
((NU8)24),
((NU8)3),
((NU8)30),
((NU8)22),
((NU8)20),
((NU8)15),
((NU8)25),
((NU8)17),
((NU8)4),
((NU8)8),
((NU8)31),
((NU8)27),
((NU8)13),
((NU8)23),
((NU8)21),
((NU8)19),
((NU8)16),
((NU8)7),
((NU8)26),
((NU8)12),
((NU8)18),
((NU8)6),
((NU8)11),
((NU8)5),
((NU8)10),
((NU8)9)}
;
