from ralium.web.webhook import WebHook
from ralium.config import WindowConfig

from ralium.element import HTMLElement
from ralium.util import UrlPath
from typing import AnyStr, List

class Window:
    def __init__(self, webhooks: List[WebHook], config: WindowConfig | None = ...) -> None: ...
    def getElementsByClassName(self, className: AnyStr) -> List[HTMLElement]: ...
    def getElementById(self, id: AnyStr) -> HTMLElement: ...
    def load_handler(self, window: Window) -> None: ...
    def display(self, url: UrlPath) -> None: ...
    def render(self, html: AnyStr) -> None: ...
    def start(self) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def shutdown(self) -> None: ...