# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).  # noqa: E501

    OpenAPI spec version: 2023-10-24
    Contact: docs@zuora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zuora_sdk
from zuora_sdk.api.contacts_api import ContactsApi  # noqa: E501
from zuora_sdk.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_contact(self):
        """Test case for create_contact

        Create a contact  # noqa: E501
        """
        pass

    def test_delete_contact(self):
        """Test case for delete_contact

        Delete a contact  # noqa: E501
        """
        pass

    def test_get_contact(self):
        """Test case for get_contact

        Retrieve a contact  # noqa: E501
        """
        pass

    def test_scrub_contact(self):
        """Test case for scrub_contact

        Scrub a contact  # noqa: E501
        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        Update a contact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
