# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).  # noqa: E501

    OpenAPI spec version: 2023-10-24
    Contact: docs@zuora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zuora_sdk
from zuora_sdk.api.actions_api import ActionsApi  # noqa: E501
from zuora_sdk.rest import ApiException


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self):
        self.api = ActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_action_post_create(self):
        """Test case for action_post_create

        Create  # noqa: E501
        """
        pass

    def test_action_post_delete(self):
        """Test case for action_post_delete

        Delete  # noqa: E501
        """
        pass

    def test_action_post_query(self):
        """Test case for action_post_query

        Query  # noqa: E501
        """
        pass

    def test_action_postquery_more(self):
        """Test case for action_postquery_more

        QueryMore  # noqa: E501
        """
        pass

    def test_action_postupdate(self):
        """Test case for action_postupdate

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
