
if __name__ == '__main__':
    from .maximum_2_satisfiability import *
    from .simultaneous_divisibility_of_linear_polynomials import *
    from .non_lr_k_context_free_grammar import *
    from .spanning_tree_parity_problem import *
    from .cosine_product_integration import *
    from .graph_isomorphism import *
    from .resource_constrained_scheduling import *
    from .sift import *
    from .minimum_length_triangulation import *
    from .quasi_real_time_language_membership import *
    from .shapley_shubik_voting_power import *
    from .fault_detection_in_directed_graphs import *
    from .minimum_weight_solution_to_linear_equations import *
    from .algebraic_equations_over_gf2 import *
    from .code_generation_on_a_one_register_machine import *
    from .non_trivial_greatest_common_divisor import *
    from .sequencing_with_release_times_and_deadlines import *
    from .ensemble_computation import *
    from .graph_genus import *
    from .serializability_of_database_histories import *
    from .crossword_puzzle_construction import *
    from .comparative_vector_inequalities import *
    from .feasible_basis_extension import *
    from .strong_in_equivalence_of_ianov_schemes import *
    from .generalized_satisfiability import *
    from .non_divisibility_of_a_product_polynomial import *
    from .three_satisfiability_3sat import *
    from .predicate_logic_without_negation import *
    from .multiprocessor_processing import *
    from .strong_inequivalence_for_monadic_recursion import *
    from .randomization_test_for_matched_pairs import *
    from .clustering import *
    from .precedence_constrained_three_processor_scheduling import *
    from .covering_for_linear_grammars import *
    from .flow_shop_scheduling import *
    from .chordal_graph_completion import *
    from .sequencing_to_minimize_tardy_task_weight import *
    from .conjunctive_satisfiability_with_functions_and_inequalities import *
    from .microcode_bit_optimization import *
    from .sequencing_to_minimize_maximum_cumulative_cost import *
    from .truth_functionally_complete_connectives import *
    from .fault_detection_with_test_points import *
    from .generalized_geography import *
    from .minimum_disjunctive_normal_form import *
    from .register_sufficiency_for_loops import *
    from .equilibrium_point import *
    from .permanent_evaluation import *
    from .cyclic_ordering import *
    from .regular_expression_inequivalence import *
    from .sequencing_to_minimize_tardy_tasks import *
    from .sequencing_with_deadlines_and_set_up_times import *
    from .composite_number import *
    from .maximum_likelihood_ranking import *
    from .deadlock_avoidance import *
    from .linear_bounded_automation_acceptance import *
    from .continuous_multiple_choice_knapsack import *
    from .inequivalence_of_finite_memory_programs import *
    from .code_generation_for_parallel_assignments import *
    from .alternating_maximum_weighted_matching import *
    from .knapsack import *
    from .finite_function_generation import *
    from .staff_scheduling import *
    from .structural_inequivalence_for_linear_grammars import *
    from .linear_programming import *
    from .decision_tree import *
    from .decoding_of_linear_codes import *
    from .preemptive_scheduling import *
    from .minimum_axiom_set import *
    from .modal_logic_s5_satisfiability import *
    from .quantified_boolean_formulas_qbf import *
    from .one_in_three_3sat import *
    from .non_containment_for_free_b_schemes import *
    from .etol_grammar_non_emptiness import *
    from .reynolds_covering_for_context_free_grammars import *
    from .cost_parametric_linear_programming import *
    from .regular_grammar_inequivalence import *
    from .sequential_truth_assignment import *
    from .finite_state_automata_intersection import *
    from .minimum_inferred_regular_expression import *
    from .safety_of_file_protection_systems import *
    from .code_generation_with_address_expressions import *
    from .exponential_expression_divisibility import *
    from .production_planning import *
    from .non_liveness_of_free_choice_petri_nets import *
    from .alternating_hitting_set import *
    from .fault_detection_in_logic_circuits import *
    from .root_of_modulus_one import *
    from .permutation_generation import *
    from .partial_order_dimension import *
    from .code_generation_with_unlimited_registers import *
    from .open_hemisphere import *
    from .non_erasing_stack_automation_acceptance import *
    from .first_order_theory_of_equality import *
    from .tree_transducer_language_membership import *
    from .context_free_programmed_language_membership import *
    from .etol_language_membership import *
    from .inequivalence_of_simple_functions import *
    from .matrix_cover import *
    from .context_sensitive_language_membership import *
    from .quasi_realtime_automation_acceptance import *
    from .variable_partition_truth_assignment import *
    from .open_shop_scheduling import *
    from .left_right_hackenbush_for_redwood_furniture import *
    from .inequivalence_of_programs_with_assignments import *
    from .chromatic_index import *
    from .subgraph_homeomorphism_for_a_fixed_graph_h import *
    from .feasibility_register_assignment import *
    from .job_shop_scheduling import *
    from .quadratic_diophantine_equations import *
    from .register_sufficiency import *
    from .scheduling_to_minimize_weighted_completion_time import *
    from .number_of_roots_for_a_product_polynomial import *
    from .finite_state_automation_inequivalence import *
    from .integer_expression_membership import *
    from .conjunctive_query_foldability import *
    from .total_unimodularity import *
    from .unification_for_finitely_presented_algebras import *
    from .annihilation import *
    from .non_tautology import *
    from .minimum_inferred_finite_state_automation import *
    from .nxn_go import *
    from .sequencing_to_minimize_weighted_tardiness import *
    from .no_wait_flow_shop_scheduling import *
    from .betweenness import *
    from .satisfiability import *
    from .generalized_hex import *
    from .consistency_of_database_frequency_tables import *
    from .non_freedom_for_loop_free_program_schemes import *
    from .reduction_of_incompletely_specified_automata import *
    from .partially_ordered_knapsack import *
    from .modal_logic_provability import *
    from .second_order_instantiation import *
    from .minimum_cardinality_key import *
    from .simply_deviated_disjunction import *
    from .precedence_constrained_scheduling import *
    from .simultaneous_incongruences import *
    from .two_way_finite_state_automation_non_emptiness import *
    from .safety_of_database_transaction_systems import *
    from .additional_key import *
    from .first_order_subsumption import *
    from .unification_with_commutative_operators import *
    from .scheduling_with_individual_deadlines import *
    from .quadratic_congruences import *
    from .programs_with_formally_recursive_procedures import *
    from .sequencing_to_minimize_weighted_completion_time import *
    from .tableau_equivalence import *
    from .generalized_instant_insanity import *
    from .reachability_for_one_conservative_petri_nets import *
    from .nxn_checkers import *
    from .matrix_domination import *
    from .minimum_weight_and_or_graph_solution import *
    from .two_processor_flow_shop_with_bounded_buffer import *
    from .comparative_divisibility import *
    from .inequivalence_of_programs_with_arrays import *
    from .integer_programming import *
    from .quadratic_programming import *
    from .satisfiability_of_boolean_expressions import *
    from .boyce_codd_normal_form_violation import *
    from .code_generation_with_unfixed_variable_locations import *
    from .not_all_equal_3sat import *
    from .square_tiling import *
    from .travelling_salesman_polytope_non_adjacency import *
    from .timetable_design import *
    from .prime_attribution_name import *
    from .generalized_kayles import *
    from .k_relevancy import *
    from .periodic_solution_recurrence_relation import *
    from .integer_knapsack import *
    from .conjunctive_boolean_query import *
