# coding: utf-8

"""
    Zuora API Reference

    REST API reference for the Zuora Billing, Payments, and Central Platform! Check out the [REST API Overview](https://www.zuora.com/developer/api-references/api/overview/).

    The version of the OpenAPI document: 2023-10-24
    Contact: docs@zuora.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class WorkflowDefinitionActiveVersionType(str, Enum):
    """
    The type of the active version. Currently the only valid value is 'Workflow::Setup'. 
    """

    """
    allowed enum values
    """
    WORKFLOW_COLON_COLON_SETUP = 'Workflow::Setup'
    WORKFLOW_COLON_COLON_INSTANCE = 'Workflow::Instance'

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowDefinitionActiveVersionType:
        """Create an instance of WorkflowDefinitionActiveVersionType from a JSON string"""
        return WorkflowDefinitionActiveVersionType(json.loads(json_str))


