
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-14T04:35:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d10c695735b3449eb0216bd00f2f83fe7cb49e22",
 "version": "4.1.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
